object_detector:
  weights_path: '../footballtracker/detection/weights/yolov8n.pt'
  classes:
    0: 'ball'
    1: 'player'  # originally goalkeeper, but keeping as player due to low acc (class imbalance)
    2: 'player'
    3: 'referee'

input_video_path: '../data/0b1495d3_0.mp4'
show_live: true
